DROP TABLE "mcc_code";
DROP TABLE "expense_category"
DROP TABLE "card_operation"
DROP TABLE "card";
DROP TABLE "cc_user";
DROP SEQUENCE s_user_id;
DROP SEQUENCE s_card_id;
DROP SEQUENCE s_card_op_id;
DROP SEQUENCE s_expense_id;
DROP SEQUENCE s_mcc_code_id;